### PR TITLE
Describe null value for VRDevice.stageParameters attribute

### PR DESCRIPTION
**Pull request by dmarcos**
Captures changes proposed in https://github.com/w3c/webvr/issues/67

### CODE REVIEW

**Comment by dmarcos** [comment]
@kearwood ?

**Comment by toji** [comment]
LGTM, but I'll let @kearwood take a look too before merging.

**Comment by dmarcos** [comment]
@kearwood I rebased this and it's ready to merge

**Comment by kearwood** [comment]
LGTM, Thanks!

**Pull request merged**
