### PR TITLE
Remove proprietary WebIDL extended attributes

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by cvan** [comment]
sorry, changes have been made since. could you rebase?

**Comment by dontcallmedom** [comment]
rebased. the generated html has more changes than the ones from just this pull request, since apparently there was an update to index.bs that wasn't mirrored to the .html.

Should I just submit changes to the .bs?

**Comment by cvan** [comment]
> Should I just submit changes to the .bs?

yep, just run `make` and you'll be good

**Comment by dontcallmedom** [comment]
that's what I had done, so I think this is ready to merge

**Comment by kearwood** [comment]
This looks good to me.

**Pull request merged**
