### PR TITLE
Multiple Frame of Reference changes

### PR DESCRIPTION
**Pull request by toji**
- move depthNear/Far to FrameOfReference
- Create FrameOfReference with constructor instead of async function

### CODE REVIEW

**Comment by toji** [comment]
Landing would fix #213

**Comment by NellWaliczek** [comment]
Hey @toji! Sorry I didn't a chance to respond to the issue that prompted this sooner :-/

I totally agree that it's unclear when depth plane changes will be applied with the current shape of the API.  I'm not sure though that depthNear and depthFar are really properties of the Frame of Reference as much as of the VR Device itself...  For example, from frame-to-frame developers can choose to use whichever frame of reference they like, and as such we risk developers accidentally having the wrong projection matrices during tracking loss because they only updated one of the frames of reference.

What about if we have these values be readonly attributes of the VRSession and have a Promise<void> setDepthNear() to change them that fulfills the promise on the rendering frame boundary.

**Comment by toji** [comment]
Updated the pull request. There were several non-controversial documentation updates rolled up into this that I pulled out and landed separately on master. Now this PR focuses more strictly on the proposed changes. Doesn't address Nell's feedback yet.

**Comment by toji** [comment]
Closing this since it's obvious they need more discussion and it's got conflicts now anyway.

**Pull request closed without merging**
